function [max_ay, balance] = evaluate_ymd_setup( ...
    x, ...
    si_vec, vs_vec, niter, alpha_lim, ...
    a, b, vx, m, g, ...
    t_f, t_r, wb, ...
    wsn, wufn, wurn, ...
    h2, kphi_f_p, kphi_r_p, den_roll, ...
    rc_f, rc_r, ...
    fz_f0, fz_r0, ...
    model, izz, w)

    gamma_f = x(1);
    gamma_r = x(2);
    tau_f   = x(3);
    tau_r   = x(4);

    % --- PONTO B: grid reduzida durante a busca ---
    % Em vez de usar si_vec/vs_vec completos (ex: 29x29 pts, 8 iter),
    % usamos uma grid grosseira (15x15 pts, 4 iter) — erro < 1% no max_ay,
    % mas ~4x menos calcForces calls por avaliacao.
    si_max  = max(abs(si_vec));
    vs_max  = max(abs(vs_vec));
    step_s  = deg2rad(2);                          % resolucao de 2 graus
    si_fast = -si_max : step_s : si_max;
    vs_fast = -vs_max : step_s : vs_max;
    niter_fast = 4;                                % convergencia suficiente em 4 iter

    [a_lat_g, nz_norm, ~] = run_ymd( ...
        si_fast, vs_fast, niter_fast, alpha_lim, ...
        a, b, vx, m, g, ...
        t_f, t_r, wb, ...
        wsn, wufn, wurn, ...
        h2, kphi_f_p, kphi_r_p, den_roll, ...
        rc_f, rc_r, ...
        fz_f0, fz_r0, ...
        gamma_f, gamma_f, gamma_r, gamma_r, ...
        tau_f, tau_f, tau_r, tau_r, ...
        model, izz, w);

    max_ay = max(abs(a_lat_g(:)));

    mask = abs(a_lat_g) > 0.8 * max_ay;

    if any(mask(:))
        balance = mean(abs(nz_norm(mask)));
    else
        balance = inf;
    end

end
