function [max_ay, balance] = evaluate_ymd_setup( ...
    x, ...
    si_vec, vs_vec, niter, alpha_lim, ...
    a, b, vx, m, g, ...
    t_f, t_r, wb, ...
    wsn, wufn, wurn, ...
    h2, kphi_f_p, kphi_r_p, den_roll, ...
    rc_f, rc_r, ...
    fz_f0, fz_r0, ...
    model, izz, w)

    gamma_f = x(1);
    gamma_r = x(2);
    tau_f   = x(3);
    tau_r   = x(4);

    [a_lat_g, nz_norm, ~] = run_ymd( ...
        si_vec, vs_vec, niter, alpha_lim, ...
        a, b, vx, m, g, ...
        t_f, t_r, wb, ...
        wsn, wufn, wurn, ...
        h2, kphi_f_p, kphi_r_p, den_roll, ...
        rc_f, rc_r, ...
        fz_f0, fz_r0, ...
        gamma_f, gamma_f, gamma_r, gamma_r, ...
        tau_f, tau_f, tau_r, tau_r, ...
        model, izz, w);

    max_ay = max(abs(a_lat_g(:)));

    mask = abs(a_lat_g) > 0.8 * max_ay;

    if any(mask(:))
        balance = mean(abs(nz_norm(mask)));
    else
        balance = inf;
    end

end