function tire = load_hoosier_tire(filename)
% Carrega os parâmetros necessários do ficheiro .tir

    tire.filename = filename;

    % básicos
    tire.FZ0 = read_tir_value(filename, 'FNOMIN');
    tire.R0  = read_tir_value(filename, 'UNLOADED_RADIUS');

    % -------- P_fy --------
    tire.P_fy = [ ...
        read_tir_value(filename, 'PCY1'), ...
        read_tir_value(filename, 'PDY1'), ...
        read_tir_value(filename, 'PDY2'), ...
        read_tir_value(filename, 'PDY3'), ...
        read_tir_value(filename, 'PEY1'), ...
        read_tir_value(filename, 'PEY2'), ...
        read_tir_value(filename, 'PEY3'), ...
        read_tir_value(filename, 'PEY4'), ...
        read_tir_value(filename, 'PKY1'), ...
        read_tir_value(filename, 'PKY2'), ...
        read_tir_value(filename, 'PKY3'), ...
        read_tir_value(filename, 'PHY1'), ...
        read_tir_value(filename, 'PHY2'), ...
        read_tir_value(filename, 'PHY3'), ...
        read_tir_value(filename, 'PVY1'), ...
        read_tir_value(filename, 'PVY2'), ...
        read_tir_value(filename, 'PVY3'), ...
        read_tir_value(filename, 'PVY4') ...
    ];

    % -------- P_mz --------
    tire.P_mz = [ ...
        read_tir_value(filename, 'QBZ1'), ...
        read_tir_value(filename, 'QBZ2'), ...
        read_tir_value(filename, 'QBZ3'), ...
        read_tir_value(filename, 'QBZ4'), ...
        read_tir_value(filename, 'QBZ5'), ...
        read_tir_value(filename, 'QBZ9'), ...
        read_tir_value(filename, 'QBZ10'), ...
        read_tir_value(filename, 'QCZ1'), ...
        read_tir_value(filename, 'QDZ1'), ...
        read_tir_value(filename, 'QDZ2'), ...
        read_tir_value(filename, 'QDZ3'), ...
        read_tir_value(filename, 'QDZ4'), ...
        read_tir_value(filename, 'QDZ6'), ...
        read_tir_value(filename, 'QDZ7'), ...
        read_tir_value(filename, 'QDZ8'), ...
        read_tir_value(filename, 'QDZ9'), ...
        read_tir_value(filename, 'QEZ1'), ...
        read_tir_value(filename, 'QEZ2'), ...
        read_tir_value(filename, 'QEZ3'), ...
        read_tir_value(filename, 'QEZ4'), ...
        read_tir_value(filename, 'QEZ5'), ...
        read_tir_value(filename, 'QHZ1'), ...
        read_tir_value(filename, 'QHZ2'), ...
        read_tir_value(filename, 'QHZ3'), ...
        read_tir_value(filename, 'QHZ4') ...
    ];
end